title: Computer Security Blog
description: "A Computer Security Blog For Hackers"
author:
  name: "Berk"
  email: "info@berk.red"
  url: "https://berk.red"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Berk"
year : "2016"
